Traceback (most recent call last):
  File "/home/sean/Documents/Work/CDS_book/book/lib/python3.10/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/home/sean/Documents/Work/CDS_book/book/lib/python3.10/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/home/sean/Documents/Work/CDS_book/book/lib/python3.10/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/home/sean/Documents/Work/CDS_book/book/lib/python3.10/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/home/sean/Documents/Work/CDS_book/book/lib/python3.10/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/home/sean/Documents/Work/CDS_book/book/lib/python3.10/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/home/sean/Documents/Work/CDS_book/book/lib/python3.10/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
atlittudes = np.linspace(0, 80000, 100)
temp = isa.get_temperature(atlittudes)
pressure = isa.get_pressure(atlittudes)
density = isa.get_density(atlittudes)
fig, ax = plt.subplots(1, 3, figsize=(10, 6), sharey=True)
labels = ["Temperature $(K)$", "Pressure $(Pa)$", "Density $(kg/m^3)$"]
for i, profile in enumerate([temp, pressure, density]):
    ax[i].plot(profile, atlittudes, color=colours.durham.ink)
    ax[i].fill_between(
        [np.min(profile), np.max(profile)],
        [0, 0],
        [10**4, 10**4],
        linestyle="--",
        color=colours.durham.ink,
        label="Troposphere",
        alpha=0.2,
    )
    ax[i].set_yticks(ax[i].get_yticks(), ax[i].get_yticks() / 1000)
    ax[i].set_ylim(0, 80000)
    ax[i].set_xlabel(labels[i])
ax[0].set_ylabel("Altitude $(km)$")
ax[1].set_title("ISA Vertical Profile up to $10km$")
ax[0].legend();
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mNameError[0m                                 Traceback (most recent call last)
Input [0;32mIn [2][0m, in [0;36m<cell line: 2>[0;34m()[0m
[1;32m      1[0m atlittudes [38;5;241m=[39m np[38;5;241m.[39mlinspace([38;5;241m0[39m, [38;5;241m80000[39m, [38;5;241m100[39m)
[0;32m----> 2[0m temp [38;5;241m=[39m [43misa[49m[38;5;241m.[39mget_temperature(atlittudes)
[1;32m      3[0m pressure [38;5;241m=[39m isa[38;5;241m.[39mget_pressure(atlittudes)
[1;32m      4[0m density [38;5;241m=[39m isa[38;5;241m.[39mget_density(atlittudes)

[0;31mNameError[0m: name 'isa' is not defined
NameError: name 'isa' is not defined

